<a href="https://colab.research.google.com/github/Aashima1511/Predicting-Model/blob/main/minor_project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
train=pd.read_csv('train (1).csv')

In [ ]:
test=pd.read_csv('test.csv')

In [ ]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [ ]:
train.info(),test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass  

(None, None)

In [ ]:
train.drop('Name',axis=1,inplace=True)
train.drop('Embarked',axis=1,inplace=True)
train.drop(['Cabin'],axis=1,inplace=True)
train.drop('Ticket',axis=1,inplace=True)
test.drop('Name',axis=1,inplace=True)
test.drop('Embarked',axis=1,inplace=True)
test.drop(['Cabin'],axis=1,inplace=True)
test.drop('Ticket',axis=1,inplace=True)


In [ ]:
train.shape,test.shape

((891, 8), (418, 7))

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    object 
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Fare         891 non-null    float64
dtypes: float64(2), int64(5), object(1)
memory usage: 55.8+ KB


In [ ]:
train['Sex'].unique()


array(['male', 'female'], dtype=object)

In [ ]:
train['Sex']=train['Sex'].map({"male":1, "female":2})
test['Sex']=test['Sex'].map({"male":1, "female":2})

In [ ]:
train['Sex'].unique()

array([1, 2])

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    int64  
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Fare         891 non-null    float64
dtypes: float64(2), int64(6)
memory usage: 55.8 KB


In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Sex          418 non-null    int64  
 3   Age          332 non-null    float64
 4   SibSp        418 non-null    int64  
 5   Parch        418 non-null    int64  
 6   Fare         417 non-null    float64
dtypes: float64(2), int64(5)
memory usage: 23.0 KB


In [ ]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Fare             0
dtype: int64

In [ ]:
test.isnull().sum()

PassengerId     0
Pclass          0
Sex             0
Age            86
SibSp           0
Parch           0
Fare            1
dtype: int64

In [ ]:
train['Age'].mode()[0]

24.0

In [ ]:
train['Age']=train['Age'].fillna(train['Age'].mode()[0])
test['Age']=test['Age'].fillna(train['Age'].mode()[0])

In [ ]:
train.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
dtype: int64

In [ ]:
test.isnull().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           1
dtype: int64

In [ ]:
train.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0            1         0       3    1  22.0      1      0   7.2500
1            2         1       1    2  38.0      1      0  71.2833
2            3         1       3    2  26.0      0      0   7.9250
3            4         1       1    2  35.0      1      0  53.1000
4            5         0       3    1  35.0      0      0   8.0500

In [ ]:
test.head()

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare
0          892       3    1  34.5      0      0   7.8292
1          893       3    2  47.0      1      0   7.0000
2          894       2    1  62.0      0      0   9.6875
3          895       3    1  27.0      0      0   8.6625
4          896       3    2  22.0      1      1  12.2875

In [ ]:
#divide the train data into x and y

In [ ]:
x=train.drop('Survived',axis=1)
y=train['Survived']

In [ ]:
x.shape,y.shape

((891, 7), (891,))

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_val,y_train,y_val=train_test_split(x,y,test_size=0.3,random_state=1,stratify=y)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_validate

In [ ]:
dt=DecisionTreeClassifier()

dt.fit(x_train,y_train)
train_pred=dt.predict(x_train)
pred=dt.predict(x_val)

acc=accuracy_score(y_val,pred)
train_acc=accuracy_score(y_train,train_pred)

train_acc,acc

(1.0, 0.7313432835820896)

In [ ]:
#model over-fitting highly

In [ ]:
confusion_matrix(y_train,train_pred)

array([[384,   0],
       [  0, 239]])

In [ ]:
confusion_matrix(y_val,pred)

array([[134,  31],
       [ 41,  62]])

In [ ]:
#model is really very poor

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
params={"criterion":("gini","entropy"),
        "max_depth":(2,3,4,6,8,10,14,16,18,20,23),
        "min_samples_split":(2,4,6,8,10,12,14)
        }
tree=DecisionTreeClassifier(random_state=1)
grid_search=GridSearchCV(estimator=tree,scoring="accuracy",param_grid=params,cv=5,verbose=True,n_jobs=-1)
grid_search.fit(x,y)

Fitting 5 folds for each of 154 candidates, totalling 770 fits


GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=1), n_jobs=-1,
             param_grid={'criterion': ('gini', 'entropy'),
                         'max_depth': (2, 3, 4, 6, 8, 10, 14, 16, 18, 20, 23),
                         'min_samples_split': (2, 4, 6, 8, 10, 12, 14)},
             scoring='accuracy', verbose=True)

In [ ]:
grid_search.best_params_

{'criterion': 'gini', 'max_depth': 6, 'min_samples_split': 14}

In [ ]:
dtc=DecisionTreeClassifier(random_state=1,criterion="gini",max_depth=6,min_samples_split=14)

dtc.fit(x_train,y_train)
train_pred=dtc.predict(x_train)
pred=dt.predict(x_val)

acc=accuracy_score(y_val,pred)
train_acc=accuracy_score(y_train,train_pred)

train_acc,acc

(0.8667736757624398, 0.7313432835820896)

In [ ]:
#model not performing great

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
params={"criterion":("gini","entropy"),
        "max_depth":range(2,23),
        "min_samples_split":range(2,15)
        }
tree=DecisionTreeClassifier()
clf=RandomizedSearchCV(tree,params,random_state=0,scoring="accuracy",cv=4,verbose=True,n_iter=250,n_jobs=-1)
clf.fit(x_train,y_train)

Fitting 4 folds for each of 250 candidates, totalling 1000 fits


RandomizedSearchCV(cv=4, estimator=DecisionTreeClassifier(), n_iter=250,
                   n_jobs=-1,
                   param_distributions={'criterion': ('gini', 'entropy'),
                                        'max_depth': range(2, 23),
                                        'min_samples_split': range(2, 15)},
                   random_state=0, scoring='accuracy', verbose=True)

In [ ]:
clf.best_params_

{'min_samples_split': 12, 'max_depth': 5, 'criterion': 'entropy'}

In [ ]:
dtc1=DecisionTreeClassifier(random_state=1,criterion="entropy",max_depth=5,min_samples_split=12)

dtc1.fit(x_train,y_train)
train_pred=dtc1.predict(x_train)
pred=dtc1.predict(x_val)

acc=accuracy_score(y_val,pred)
train_acc=accuracy_score(y_train,train_pred)

train_acc,acc

(0.8619582664526485, 0.7686567164179104)